version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olya-app
    restart: always
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - ./public:/app/public # Монтируем папку для статики
    ports:
      - "25565:25565"
    environment:
      - DATABASE_URL=postgres://neondb_owner:npg_Xotmfb9lNFS6@ep-odd-silence-a2kevyft-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres